// Core types
export { definePlugin } from './types';
export type {
  HomePlugin,
  HomePluginManifest,
  HomePluginQuickAction,
  HomePluginActionCategory,
  HomePluginTab,
  HomePluginIntent,
  HomePluginContext,
  CapabilityId,
  PluginActionConfig,
  PluginTabConfig,
  PluginThemeConfig,
  PluginStateMachineConfig,
  PluginBreakpointConfig,
  PluginContext,
  PluginRenderProps,
  PluginRuntimeContext,
  PluginSetupContext,
  ResolvedCapabilities,
  AgentCallingCapability,
  AgentCallInput,
  ResultExtractionCapability,
  BreakpointResumeCapability,
  BreakpointData,
  PersistenceCapability,
  StreamingDisplayCapability,
  ChatDisplayMessage,
  ThemeCapability,
  AnimationsCapability,
  ModalsCapability,
} from './types';

// Registry (quick actions)
export {
  registerPlugin,
  unregisterPlugin,
  getAllPlugins,
  applyDisabledPluginIds,
  applySidebarPluginPreferences,
  getCategories,
  getActions,
  getPinnedActions,
  getCollapsibleActions,
  getTabs,
  getIntent,
  getAllIntents,
  getActionsGrouped,
  registerIntentHandler,
  unregisterIntentHandler,
  getIntentHandler,
  dispatchHomeAction,
} from './registry';
